version: "3"
services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /opt/AppFolder/frontend/:/usr/share/nginx/html/
      - /opt/AppFolder/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    environment:
      BACKEND_DNS: http://backend:5000/
    restart: always
  backend:
  #n Circleci "publish-python-image" stage is creating a image for python code and uploading to dockerhub. Then docker-compose will get that docker image and run it on server
    image: wardrobewizard/python-app:latest # This is the image name of the backend service that we have built in circleci
    ports:
      - "5000:5000"
    restart: always