version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      # Specify the desired Python version
      - image: cimg/python:3.10  # Adjust the Python version as needed

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      # Adjust the path and name of the dependency file if needed
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      # Run your tests using the appropriate command
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test
